### PR TITLE
Split ctrlp#setlines() for ctrlp#init().  Fixes ctrlpvim/ctrlp.vim#463

### PR DESCRIPTION
**Pull request by ezequielv**
* Issue:

Opening `ctrlp` in certain modes (`:CtrlPBufTag`, `:CtrlPLine`) seems to
trigger a partially deffective intialisation (for example, syntax
highlighting not working as expected).

* Changes:

`ctrlp#setlines()` has been split in two, as the second part (now in
`s:setlines_post()`) seems to need `&filetype`, and `s:DetectFileType()`
seems to need the first part of the old `ctrlp#setlines()` (now in
`s:setlines_pre()`).

### CODE REVIEW

**Comment by ezequielv** [comment]
For more details on the fix itself, please see the thread in #463.

**Comment by tacahiroy** [comment]
Thanks for your PR.
I've done quick check for this with Vim 8.1.466 and looked working nicely.

**Comment by mattn** [comment]
Good to merge?

**Comment by tacahiroy** [comment]
It's good to go from my pov.

**Comment by mattn** [comment]
Thank you

**Comment by ezequielv** [comment]
Thank you for merging this :+1:. I've got a number of fixes for other issues I've encountered, so this merge is encouraging :smile:

**Pull request merged**
