### PR TITLE
New buffer explorer mode with highlighting

### PR DESCRIPTION
**Pull request by noscript**
Referring to #37. Fixes for issues #46 and #47 are included into this PR.

### CODE REVIEW

**Comment by amadeus** [comment]
Any updates on this? Would love to start using this again.

**Comment by mattn** [comment]
@noscript any update on this?

**Comment by noscript** [comment]
Thanks for reminder. Let me try to rebase it against master and we will continue from there. I will do it during the week.

**Comment by noscript** [comment]
Rewrote few things, and it works again. Let me still check previously reported issues...

**Comment by noscript** [comment]
@amadeus At the moment of issuing ':bd' CtrlP is the current buffer, so the other buffer gets closed along with the window. Workaround to keep the window open isn't going to be concise and not worth it. I had to disallow to delete current buffer.

**Comment by noscript** [comment]
Ok guys, it's ready for testing.

**Comment by mattn** [comment]
merged https://github.com/ctrlpvim/ctrlp.vim/commit/6c79adff795f30c7f4a5d208bf62020a8bae33e8

thanks! :+1:

**Comment by mattn** [comment]
Sorry, I merged, but reverted because this change break prompt.

**Comment by noscript** [comment]
How can I reproduce that?

**Comment by mattn** [comment]
1. disable all of user customized options.
2. open some buffers
3. CtrlPBuffer
4. move down/up cursor

**Comment by noscript** [comment]
Cannot reproduce. My `.vimrc`:
```
set nocompatible
let s:test_dir  = expand("$HOME") . "/.vim_test~"
exec ":source ". s:test_dir . "/pathogen.vim"
execute pathogen#infect(s:test_dir . '/{}')
syntax on
filetype plugin indent on
```
ctrlp-naked

**Comment by mattn** [comment]
Sorry, I was my fault.

**Pull request merged**
