### PR TITLE
Reflect "g:ctrlp_match_current_file" in CtrlPMRUFiles even when using "g:ctrlp_match_func"

### PR DESCRIPTION
**Pull request by hokorobi**
Would it be useful to add an option to CtrlPBuffer to hide the current buffer?
Documentation has not yet been updated.

### CODE REVIEW

**Comment by mattn** [comment]
LGTM

**Comment by hokorobi** [comment]
Thank you for your comment.
I will update the documentation.

**Comment by hokorobi** [comment]
I noticed that the option "ctrlp_match_current_file" exists.
This option is not reflected if "g:ctrlp_match_func" was set.
I didn't realize this as I use [ctrlp-matchfuzzy](https://github.com/mattn/ctrlp-matchfuzzy).

Well, if I want to get the expected behaviour, it would be better to reflect ‘ctrlp_match_current_file’ only in CtrlPMRUFiles, rather than creating a new option.

**Comment by hokorobi** [comment]
I tried it like this. Please check.

**Comment by mattn** [comment]
Good catch. Thanks. I'll look into it in later.

**Comment by mattn** [comment]
Thank you

**Comment by hokorobi** [comment]
Thank you.

**Pull request merged**
