### PR TITLE
use getcurpos/setpos instead of winsaveview/winrestview

### LINKED ISSUE #256: Performance regression for s:PrtSelectMove
After upgrading to the newest version of this plugin, moving in the results window via `s:PrtSelectMove` is laggy. I guess this behaviour has been introduced by https://github.com/ctrlpvim/ctrlp.vim/commit/95eb1ddd6f91051c287392a20f406836a11b2a37 which introduced calls to `winsaveview` and `winrestview`. When i use a version from before that commit, the issue is not apparent. The cursor jumps to the end of the line before jumping to the line above / below and restoring cursor position on the `>` symbol.

### PR DESCRIPTION
**Pull request by mattn**
Close #256 

@jonathanewerner @tacahiroy Could you please try this?

### CODE REVIEW

**Comment by tacahiroy** [comment]
I don't see any differences between them. I mean both implementations work well.
So if @jonathanewerner confirms this PR improves performance it's ok.

**Comment by jonathanewerner** [comment]
No, the felt performance is identical. 
I switched back to https://github.com/kien/ctrlp.vim for the time being because perf is good there. (But other bugs are present :/)

You can't see it really well because of the framerate, but here is a visual comparison:

**kien/ctrlp.vim**
kien/ctrlp.vim

Its very fluid, even more in the up motion (fps is like twice as high for up motion)

**this repo**
this repo

It janky & the cursor jumps to the end of line shortly for each line which probably is the main culprit..

**Comment by mattn** [comment]
@jonathanewerner have you seen https://github.com/ctrlpvim/ctrlp.vim/pull/186 ?

**Comment by mattn** [comment]
And did you try this patch?

**Comment by mattn** [comment]
okay, I'll merge this. and if you still have problem, please file new issue.

**Comment by Roguelazer** [comment]
I think this broke something; ctrlp now only works on the super-modern Vim I have installed from Homebrew; in the slightly older MacVim, I get the following error:
```
E121: Undefined variable: pos
E116: Invalid arguments for function setpos
```

Working version:
```
% /usr/local/bin/vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 14 2016 16:34:13)
MacOS X (unix) version
Included patches: 1-1910
Compiled by Homebrew
```

Non-working version:
```
% vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 21 2014 14:54:22)
MacOS X (unix) version
Included patches: 1-258
Compiled by Bjorn Winckler <bjorn.winckler@gmail.com>
```

**Comment by mattn** [comment]
Could you please try this? https://github.com/ctrlpvim/ctrlp.vim/commit/8c0618c8c2561a50f661e40fce40f07837f20a15

**Comment by jonathanewerner** [comment]
What does #186 have to do with this?

**Comment by mattn** [comment]
kien/ctrlp move up cursor if set `let g:ctrlp_lazy_update = 1`

**Comment by Roguelazer** [comment]
@mattn it works now, thanks!

**Comment by mattn** [comment]
:clap:

**Pull request merged**
