### PR TITLE
Add linux-like commands to move search results.

### PR DESCRIPTION
**Pull request by blainesch**
Control+n is used to move down, and Control+p is used to move up in most select boxes.

Good examples of this would be the terminal for scrolling up/down previous commands. Another good one includes Chrome when using the search-able address bar. Lastly, VIM (netrw) uses these keys to scroll up/down directory listings in the normal directory view.

### CODE REVIEW

**Comment by blainesch** [comment]
Related to kien/ctrlp.vim/pull/653

**Comment by afaur** [comment]
:+1:

**Comment by mattn** [comment]
`<c-n>` and `<c-p>` is currently assigned to move up/down for history.
https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp.vim#L123-L124

**Comment by blainesch** [comment]
@mattn but but ]:

**Pull request closed without merging**
