### PR TITLE
Add support for terminal buffers on neovim

### PR DESCRIPTION
**Pull request by ferranpm**
It would be nice to treat terminals in neovim as buffers accessible through CtrlP.

### CODE REVIEW

**Comment by osa1** [comment]
:+1: for this.

**Comment by rockneverdies55** [comment]
:+1:

**Comment by mattn** [comment]
Is there another way to confirm to check neovim is running? `v:progname` ?

**Comment by mattn** [comment]
please add new `s:` function for checking neovim is runninng, and buftype is `terminal`.

**Comment by JunfengJia** [comment]
Any update for this? It's useful.

**Comment by mattn** [comment]
waiting for @ferranpm

**Comment by ferranpm** [comment]
Done, is this better?

**Comment by mattn** [comment]
where is `s:isneovimterminal` ?

**Comment by ferranpm** [comment]
in `autoload/ctrlp.vim` just before the `s:getenv` function.

**Comment by mattn** [comment]
Ah, sorry. I missed it.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
