### PR TITLE
Optimize s:fnesc and s:usrign

### PR DESCRIPTION
**Pull request by mattn**
Optimized s:fnesc with avoiding check features.
Optimized s:usrign with making short-path of if/else/endif
Optimized with using get(dict, key, default)

### CODE REVIEW

**Comment by mattn** [comment]
EjaN1xfUYAcX3jj

**Comment by mattn** [comment]
@tacahiroy Could you please review this?

**Comment by tacahiroy** [comment]
Sure. will do

**Comment by tacahiroy** [comment]
LGTM

**Comment by tacahiroy** [comment]
I have checked the behaviour on my local and does look good to me.

**Comment by mattn** [comment]
Thanks!

**Pull request merged**
