### PR TITLE
[Experimental] Asynchronized

### PR DESCRIPTION
**Pull request by mattn**
Using job_start()

TODO

* lazy update prompt
* close CtrlP with kill job

### CODE REVIEW

**Comment by mattn** [comment]
related issue #200

**Comment by prabirshrestha** [comment]
Super excited about this. Would love it see it working in both vim and neovim.

What about custom async sources so that `ctrlp#someplugin#init(),#accept` can be async too?
Useful for plugins that need to make http request like cdnjs, github issues, npm. Or I can just start a job and call `ctrlp#addfile` anytime. Any examples for this type of scenario?

Then all we need is async support from [webapi-vim](https://github.com/mattn/webapi-vim);

**Comment by ludovicchabant** [comment]
Hey @mattn, how does this effectively change the way CtrlP behaves currently? Do you see the list of files populating the prompt list gradually instead of having Vim freeze and then show you the prompt list in one go?

If that's the case, is there any notable slow down with the async version? (I'm assuming that it would actually be a bit slower for Vim to synchronize the data structures, and refresh the UI multiple times)

How hard would it be to also use jobs for the normal (non-user cmd) listing?

Thanks!

**Comment by mattn** [comment]
See https://twitter.com/mattn_jp/status/707502130760822784

**Comment by ludovicchabant** [comment]
Ah cool, thanks. I'd say go for it! It's disabled by default anyway so some of us can enable it and try it for a while.

**Comment by prabirshrestha** [comment]
That does look fast :shipit:

**Comment by ludovicchabant** [comment]
Hey @mattn, I have a huge project at work that's a good fit for this, but after trying your PR I don't get the CtrlP list populating "in real time" -- it just gets populated at the end in one go. I did double check that it used the `job_start` codepath... but I'm not sure what makes CtrlP display the filenames as they come in? The job callback just adds them to the list, but nothing actually refreshes anything?

If, while the job still runs, I close and reopen CtrlP I do get the intermediate list, which grows every time I close and reopen CtrlP, but it doesn't do anything while CtrlP is open?

**Comment by mattn** [comment]
>The job callback just adds them to the list, but nothing actually refreshes anything?

Yes, currently, to update the list, need to move cursor.

**Comment by prabirshrestha** [comment]
@mattn any updates on this?

**Comment by mattn** [comment]
Vim 8 is released. So We can start improving this.

**Comment by tracyone** [comment]
cool! can't wait.

**Pull request merged**
