### PR TITLE
added option g:open_single_match

### PR DESCRIPTION
**Pull request by ggVGc**
Hey, I added this option so that if there is only one match when CtrlP is opened, it jumps to that instead of opening the window. This is mostly useful together with CtrlP-Funky for me, but maybe others would like it.

### CODE REVIEW

**Comment by ludovicchabant** [comment]
Looks good, except for the tiny cosmetic detail of calling that new function "ExitIfSingleCandidate" (capital "E") to conform to the rest of the code.

**Comment by ggVGc** [comment]
Pushed new version where the option is now a list containing the names of the extensions that should auto open with only one match, since I think that works better.
I.e let g:ctrlp_open_single_match = ['funky', 'buffer']
Also renamed the function to have a capital E, although to be fair the names in ctrlp are already inconsistent with most of them being all lowercase.

**Comment by tacahiroy** [comment]
This does work for only extensions, doesn't it? I mean this doesn't work for 'buffers' mode.
Coz `s:getextvar('lname')` is checked before `s:ExitIfSingleCandidate()` called.
https://github.com/ggVGc/ctrlp.vim/commit/193d1764d7ff0ae69eddb06ee8c92d7697b213dc#diff-c9de02bff2ec6d5e66b2f5f71beb595dR2345

I guess `s:itemtype` also needs to be checked to get this working for modes defined internally such as `files`, `buffers` and `mrufiles`.
Note that `s:itemtype` is number that corresponds these modes like:
* `files` = 0
* `buffers` = 1
* `mrufiles` = 2

**Comment by ggVGc** [comment]
Yeah, sorry about that. Made it work for all modes now, and also made it so either lname or sname can be used in the option.

**Comment by ggVGc** [comment]
I have been using this now for a while, and it works good for me. Are there any other complaints that should be fixed to get this merged, or is the PR not of interest?

**Comment by ludovicchabant** [comment]
Sorry I'm slow these days.
I'm a bit confused about how to try this thing out, and how useful it is... it's supposed to open the first match if it's the only one? But, say, in case of `buffers`, that means you only have one buffer currently open? How is that useful, especially since this means you current buffer is it? Seems confusing too for other things like `mrufiles`.
How do you use it with CtrlP-Funky?

**Comment by ggVGc** [comment]
The option is not very useful when launching ctrlp without any arguments, but it becomes nice when launching with g:ctlrp_default_input to something. For example with ctrlp-funky, I have a mapping that sets ctrlp_default_input to the word under cursor, then launches ctrlp-funky. This will almost always have only one match, but ctrlp still opens and I have to press enter to close it and go to the match. With this option, ctrlp-funky can act just like gd, and just go straight to the function definition in the common case where there is only one match.
This ticket also spoke about wanting to do exactly this thing: #28

**Comment by bkudria** [comment]
Seconding, this makes https://github.com/bkudria/ctrlp-related very useful. Much thanks to @ggVGc for implementing this!

**Comment by ludovicchabant** [comment]
Ok thanks! I was able to test it. It's indeed pretty neat when you have the mappings to use it. How do you reset `g:ctrlp_default_input` though? Isn't there a way to insert the word under the cursor after CtrlP opened the prompt? (I haven't figured a way to do that though).
Either way, if everybody's OK, I can merge it.

**Comment by ggVGc** [comment]
I have this mapping currently, https://gist.github.com/e86c30e1fa21da715e1b
I was thinking about adding a way of calling CtrlP with set one-time input, overriding ctrlp_default_input for that invocation. That'd be a separate PR though.

**Comment by ludovicchabant** [comment]
Ah yeah that's what I had to do too. Yeah I think that separate PR would be nice for this kind of scenario :)

**Comment by bkudria** [comment]
@ludovicchabant Ok to merge. Do we need anything else?

**Comment by tacahiroy** [comment]
@ggVGc Do you have the same configuration as the gist for funky?
I copied and made a bit modification for that gist like: https://gist.github.com/tacahiroy/ec77be1208e7ec1d6e55
I got the error below if I executed `gd` on a function name:
```
Error detected while processing function <SNR>2_tagsUnderCursor..ctrlp#funky#funky..ctrlp#init..<SNR>62_ExitIfSingleCandidate..<SNR>62_Upd
ate..<SNR>62_Render..<SNR>62_highlight:
line   53:
E28: No such highlight group name: CtrlPLinePre
```
Do you reproduce it?
The problem is on funky's side perhaps, however, I don't have enough time to do more investigation for now. I'll have a chance to look at this some time later.

**Comment by tacahiroy** [comment]
This resolves the problem, not sure why `CtrlPLinePre` is not defined in my case though.
```patch
diff --git i/autoload/ctrlp.vim w/autoload/ctrlp.vim
index ad3d4b1..c21bf3a 100644
--- i/autoload/ctrlp.vim
+++ w/autoload/ctrlp.vim
@@ -1724,7 +1724,9 @@ fu! s:highlight(pat, grp)
 			endfor
 		en
 
-		cal matchadd('CtrlPLinePre', '^>')
+		if hlexists('CtrlPLinePre')
+			cal matchadd('CtrlPLinePre', '^>')
+		en
 	en
 endf
 ```

**Comment by ludovicchabant** [comment]
Done! Thanks everyone.

@tacahiroy: The other place where `CtrlPLinePre` gets used, there is a similar `if hlexists` statement around it so it may be a good idea to add it there as well like you did... Looks like `CtrlPLinePre` can be undefined in some situations, but I don't really understand that `if` statement around it. Looks unrelated, though, since the early exit for a single match happens after `ctrlp#syntax`.

**Comment by lervag** [comment]
Just mentioning: This option lacks proper documentation.

**Comment by ggVGc** [comment]
yeah, sorry, I forgot about that. Travelling atm, but will get make a PR within the next few days for it. Thanks for the reminder!

**Comment by lervag** [comment]
No problem! I'm happy to have found a living fork of `ctrlp`, since this is one of my absolute favorite vim plugins.

**Comment by ggVGc** [comment]
Made a PR with docs now, #113

**Pull request merged**
